version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dataharbor
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
    volumes:
      - ./backend:/app

  # Frontend service
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true" # Required for file watching in some environments
    depends_on:
      - backend

  # Database service
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dataharbor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Optional pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dataharbor.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  db_data:
