version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/dataharbor"

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dataharbor

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
